// Generated from: tests\e2e\features\venue-management.feature
import { test } from "../../../../tests/e2e/fixtures/index.ts";

test.describe('Venue management', () => {

  test.beforeEach('Background', async ({ Given, page }, testInfo) => { if (testInfo.error) return;
    await Given('I navigate to "/venues/management"', null, { page }); 
  });
  
  test('All main form sections are rendered', { tag: ['@authenticated'] }, async ({ Then, And, page }) => { 
    await Then('I should see the venue name input', null, { page }); 
    await And('I should see the "Locations" tab', null, { page }); 
    await And('I should see the "Equipment" tab', null, { page }); 
    await And('I should see the location name input', null, { page }); 
    await And('I should see a "Cancel" button', null, { page }); 
    await And('I should see a "Create Venue" button', null, { page }); 
    await And('I should see the layer name input', null, { page }); 
  });

  test('Create Venue button is disabled until a venue name is entered', { tag: ['@authenticated'] }, async ({ When, Then, page }) => { 
    await Then('the "Create Venue" button should be disabled', null, { page }); 
    await When('I fill the venue name with "Test Arena"', null, { page }); 
    await Then('the "Create Venue" button should be enabled', null, { page }); 
    await When('I clear the venue name', null, { page }); 
    await Then('the "Create Venue" button should be disabled', null, { page }); 
  });

  test('Equipment tab shows its input; switching tabs works', { tag: ['@authenticated'] }, async ({ When, Then, page }) => { 
    await When('I click the "Equipment" tab', null, { page }); 
    await Then('I should see the equipment name input', null, { page }); 
    await When('I click the "Locations" tab', null, { page }); 
    await Then('I should see the location name input', null, { page }); 
  });

  test('Cancel button navigates back to venue selection', { tag: ['@authenticated'] }, async ({ When, Then, And, page }) => { 
    await When('I fill the venue name with "Unfinished Venue"', null, { page }); 
    await And('I click the "Cancel" button', null, { page }); 
    await Then('the URL should be "/venues/selection"', null, { page }); 
    await And('I should see the "Venue Selection" or "Your Venues" heading', null, { page }); 
  });

  test('Submitting a venue name saves it and redirects to selection', { tag: ['@authenticated'] }, async ({ When, Then, And, page, scenarioState }) => { 
    await When('I create a venue with a unique name', null, { page, scenarioState }); 
    await Then('the URL should be "/venues/selection"', null, { page }); 
    await And('the newly created venue should be visible', null, { page, scenarioState }); 
  });

  test('Search filter filters and clears venue list', { tag: ['@authenticated'] }, async ({ When, Then, page, scenarioState }) => { 
    await When('I create two venues with unique names', null, { page, scenarioState }); 
    await Then('both created venues should be visible', null, { page, scenarioState }); 
    await When('I search for the first venue', null, { page, scenarioState }); 
    await Then('only the first venue should be visible', null, { page, scenarioState }); 
    await When('I clear the search', null, { page }); 
    await Then('both created venues should be visible', null, { page, scenarioState }); 
    await When('I search for "zzz-no-match-xyz"', null, { page }); 
    await Then('neither created venue should be visible', null, { page, scenarioState }); 
  });

  test('Adding a location appears in the list', { tag: ['@authenticated'] }, async ({ When, Then, page }) => { 
    await When('I add a location named "Medical Tent"', null, { page }); 
    await Then('I should see the text "Medical Tent"', null, { page }); 
  });

  test('Adding equipment appears in the list', { tag: ['@authenticated'] }, async ({ When, Then, And, page }) => { 
    await When('I click the "Equipment" tab', null, { page }); 
    await And('I add equipment named "Gurney 1"', null, { page }); 
    await Then('I should see the text "Gurney 1"', null, { page }); 
  });

  test('A location can be deleted', { tag: ['@authenticated'] }, async ({ When, Then, page }) => { 
    await When('I add a location named "Temp Location"', null, { page }); 
    await Then('I should see the text "Temp Location"', null, { page }); 
    await When('I delete the location "Temp Location"', null, { page }); 
    await Then('I should not see the text "Temp Location"', null, { page }); 
  });

  test('An equipment item can be deleted', { tag: ['@authenticated'] }, async ({ When, Then, And, page }) => { 
    await When('I click the "Equipment" tab', null, { page }); 
    await And('I add equipment named "Temp Gurney"', null, { page }); 
    await Then('I should see the text "Temp Gurney"', null, { page }); 
    await When('I delete the equipment "Temp Gurney"', null, { page }); 
    await Then('I should not see the text "Temp Gurney"', null, { page }); 
  });

  test('Multiple locations can be added', { tag: ['@authenticated'] }, async ({ When, Then, And, page }) => { 
    await When('I add a location named "Location A"', null, { page }); 
    await And('I add a location named "Location B"', null, { page }); 
    await Then('I should see the text "Location A"', null, { page }); 
    await And('I should see the text "Location B"', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\e2e\\features\\venue-management.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":9,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then I should see the venue name input","stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"And I should see the \"Locations\" tab","stepMatchArguments":[{"group":{"start":17,"value":"\"Locations\"","children":[{"start":18,"value":"Locations","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"And I should see the \"Equipment\" tab","stepMatchArguments":[{"group":{"start":17,"value":"\"Equipment\"","children":[{"start":18,"value":"Equipment","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I should see the location name input","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And I should see a \"Cancel\" button","stepMatchArguments":[{"group":{"start":15,"value":"\"Cancel\"","children":[{"start":16,"value":"Cancel","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And I should see a \"Create Venue\" button","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Venue\"","children":[{"start":16,"value":"Create Venue","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And I should see the layer name input","stepMatchArguments":[]}]},
  {"pwTestLine":20,"pickleLine":18,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Venue\" button should be disabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Venue\"","children":[{"start":5,"value":"Create Venue","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When I fill the venue name with \"Test Arena\"","stepMatchArguments":[{"group":{"start":27,"value":"\"Test Arena\"","children":[{"start":28,"value":"Test Arena","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Venue\" button should be enabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Venue\"","children":[{"start":5,"value":"Create Venue","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When I clear the venue name","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Venue\" button should be disabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Venue\"","children":[{"start":5,"value":"Create Venue","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":28,"pickleLine":25,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"When I click the \"Equipment\" tab","stepMatchArguments":[{"group":{"start":12,"value":"\"Equipment\"","children":[{"start":13,"value":"Equipment","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then I should see the equipment name input","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When I click the \"Locations\" tab","stepMatchArguments":[{"group":{"start":12,"value":"\"Locations\"","children":[{"start":13,"value":"Locations","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then I should see the location name input","stepMatchArguments":[]}]},
  {"pwTestLine":35,"pickleLine":31,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":32,"keywordType":"Action","textWithKeyword":"When I fill the venue name with \"Unfinished Venue\"","stepMatchArguments":[{"group":{"start":27,"value":"\"Unfinished Venue\"","children":[{"start":28,"value":"Unfinished Venue","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"And I click the \"Cancel\" button","stepMatchArguments":[{"group":{"start":12,"value":"\"Cancel\"","children":[{"start":13,"value":"Cancel","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then the URL should be \"/venues/selection\"","stepMatchArguments":[{"group":{"start":18,"value":"\"/venues/selection\"","children":[{"start":19,"value":"/venues/selection","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"And I should see the \"Venue Selection\" or \"Your Venues\" heading","stepMatchArguments":[]}]},
  {"pwTestLine":42,"pickleLine":37,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"When I create a venue with a unique name","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then the URL should be \"/venues/selection\"","stepMatchArguments":[{"group":{"start":18,"value":"\"/venues/selection\"","children":[{"start":19,"value":"/venues/selection","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"And the newly created venue should be visible","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":42,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When I create two venues with unique names","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then both created venues should be visible","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When I search for the first venue","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then only the first venue should be visible","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"When I clear the search","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":48,"keywordType":"Outcome","textWithKeyword":"Then both created venues should be visible","stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When I search for \"zzz-no-match-xyz\"","stepMatchArguments":[{"group":{"start":13,"value":"\"zzz-no-match-xyz\"","children":[{"start":14,"value":"zzz-no-match-xyz","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then neither created venue should be visible","stepMatchArguments":[]}]},
  {"pwTestLine":59,"pickleLine":52,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When I add a location named \"Medical Tent\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Medical Tent\"","children":[{"start":24,"value":"Medical Tent","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then I should see the text \"Medical Tent\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Medical Tent\"","children":[{"start":23,"value":"Medical Tent","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":64,"pickleLine":56,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When I click the \"Equipment\" tab","stepMatchArguments":[{"group":{"start":12,"value":"\"Equipment\"","children":[{"start":13,"value":"Equipment","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"And I add equipment named \"Gurney 1\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Gurney 1\"","children":[{"start":23,"value":"Gurney 1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then I should see the text \"Gurney 1\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Gurney 1\"","children":[{"start":23,"value":"Gurney 1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":70,"pickleLine":61,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When I add a location named \"Temp Location\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Temp Location\"","children":[{"start":24,"value":"Temp Location","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"Then I should see the text \"Temp Location\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Temp Location\"","children":[{"start":23,"value":"Temp Location","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When I delete the location \"Temp Location\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Temp Location\"","children":[{"start":23,"value":"Temp Location","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then I should not see the text \"Temp Location\"","stepMatchArguments":[{"group":{"start":26,"value":"\"Temp Location\"","children":[{"start":27,"value":"Temp Location","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":77,"pickleLine":67,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"When I click the \"Equipment\" tab","stepMatchArguments":[{"group":{"start":12,"value":"\"Equipment\"","children":[{"start":13,"value":"Equipment","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":69,"keywordType":"Action","textWithKeyword":"And I add equipment named \"Temp Gurney\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Temp Gurney\"","children":[{"start":23,"value":"Temp Gurney","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"Then I should see the text \"Temp Gurney\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Temp Gurney\"","children":[{"start":23,"value":"Temp Gurney","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When I delete the equipment \"Temp Gurney\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Temp Gurney\"","children":[{"start":24,"value":"Temp Gurney","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then I should not see the text \"Temp Gurney\"","stepMatchArguments":[{"group":{"start":26,"value":"\"Temp Gurney\"","children":[{"start":27,"value":"Temp Gurney","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":85,"pickleLine":74,"tags":["@authenticated"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I navigate to \"/venues/management\"","isBg":true,"stepMatchArguments":[{"group":{"start":14,"value":"\"/venues/management\"","children":[{"start":15,"value":"/venues/management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"When I add a location named \"Location A\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Location A\"","children":[{"start":24,"value":"Location A","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"And I add a location named \"Location B\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Location B\"","children":[{"start":24,"value":"Location B","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then I should see the text \"Location A\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Location A\"","children":[{"start":23,"value":"Location A","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"And I should see the text \"Location B\"","stepMatchArguments":[{"group":{"start":22,"value":"\"Location B\"","children":[{"start":23,"value":"Location B","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end