name: Deploy on Realease

on:
  release:
    types: [published]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate semver tag
        run: |
          if [[ "${{ github.event.release.tag_name }}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?(\+[a-zA-Z0-9.]+)? ]]; then
          echo "Valid semver tag: ${{ github.event.release.tag_name }}"
          else
          echo "❌ '${{ github.event.release.tag_name }}' is not a valid semver tag"
          exit 1
          fi

  install:
    needs: check
    uses: ./.github/workflows/install.yml
    with:
      sha: ${{ github.sha }}
    secrets: inherit

  deploy-netlify:
    needs: install
    runs-on: ubuntu-latest
    environment: production
    if: needs.install.result == 'success'
    steps:        
      - name: Download artifact
        uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ needs.install.outputs.artifact-name }}
          path: .
      
      - name: List artifact files
        run: ls ${{ steps.download.outputs.download-path }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}
          DISABLE_TELEMETRY: true
      
      - name: Deploy
        run: echo 'Deploying ...' 
