name: Install deps project and upload artifact

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
    outputs:
      artifact-name:
        description: "Name of the uploaded install deps artifact"
        value: ${{ jobs.install.outputs.artifact-name }}

jobs:
    
  install:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-${{ inputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: npm
      - run: npm ci 
      - run: npm run lint

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ inputs.sha }}
          path: .
          retention-days: 1
          if-no-files-found: error
          include-hidden-files: true
